### ISSUE TITLE
npm ERR! 404 Not Found: @ui5/builder@^1.3.3

### ISSUE THREAD

**Issue by pwasem** [SAP/karma-ui5#107]
There is an issue with peer dependency `@ui5/builder` when running `npm install`:

```sh
[2019-08-28T11:13:20.571Z] npm ERR! code E404
[2019-08-28T11:13:20.571Z] npm ERR! 404 Not Found: @ui5/builder@^1.3.3
```

`package.json` looks like this:
```json
 {
    "devDependencies": {
      "karma-ui5": "^1.0.1",
    }
}
```

Could you please *lock* the peer dependencies?

Thank you in advance!

**Comment by matz3** [comment]
The problem doesn't seem to be related to this plugin.

[@ui5/builder v1.4.2](https://github.com/SAP/ui5-builder/releases/tag/v1.4.2) has been released this morning. In case you are not using the public npm registry, but e.g. an internal mirror, this version might not be cached yet, but the registry already lists `v1.4.2` as latest. Therefore downloading the tar fails.
This needs to be addressed in the npm registry.
