### ISSUE TITLE
App type library running karma in html mode

### ISSUE THREAD

**Issue by shahzeb79** [SAP/karma-ui5#160]
Hi Colleagues,
I face a problem that when i try to run karma ui5 on my app of type reuselibrary(in Html mode).
My [test file](https://<removed-internal-domain>/plugins/gitiles/fnf/QD/fin.central.lib/+/refs/heads/master/test/qunit/tests/main.qunit.testsuite.html) search for loading ui5 resources locally and not from CDN. 

If i use CDN explicitly in src of bootstrap, than it works fine in karma like:
```
<script id="sap-ui-bootstrap" 
	type="text/javascript"
	src="https://sapui5.hana.ondemand.com/resources/sap-ui-core.js"
	data-sap-ui-theme="sap_bluecrystal"
	data-sap-ui-noConflict="true"
	data-sap-ui-libs=""
	data-sap-ui-modules="sap.ui.core.plugin.LessSupport" />
```
But dont work like:
```
<script id="sap-ui-bootstrap" 
	type="text/javascript"
	src="../../../resources/sap-ui-core.js"
	data-sap-ui-theme="sap_bluecrystal"
	data-sap-ui-noConflict="true"
	data-sap-ui-libs=""
	data-sap-ui-modules="sap.ui.core.plugin.LessSupport" />
```
Any thoughts on it?

**Comment by matz3** [comment]
I guess your project doesn't have proper UI5 Tooling dependencies defined or there's a problem with the configured server (when using ui5 "url" config).

**Comment by shahzeb79** [comment]
@matz3 
```
"@ui5/cli": "^1.5.4",
    "karma": "^4.1.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage": "^1.1.2",
    "karma-firefox-launcher": "1.1.0",
    "karma-htmlfile-reporter": "^0.3.8",
    "karma-junit-reporter": "^1.2.0",
    "karma-qunit": "^3.1.2",
    "karma-ui5": "^1.0.1",
    "karma-webdriver-launcher": "^1.0.5",
    "qunit": "^2.9.2"
```
This is my dependency list in package.json

**Comment by matz3** [comment]
You might have a look into our sample app to see how dependencies need to be defined:
https://github.com/SAP/openui5-sample-app

However, currently only OpenUI5 libraries are supported that way.
Otherwise you need to separately start a web server with your UI5 dependencies and configure the "ui5 url" in the karma config so that it is used.

**Comment by shahzeb79** [comment]
But for the App of type Application, we use ui5 url as https://sapui5.hana.ondemand.com/ and in that case it works, just additional libraries we need to extract in webapp folder and they get served. You mean in case of app type "library" , its not supported and we have to serve them?

**Comment by matz3** [comment]
No, that should behave the same.
Can you send me some details via E-Mail?

**Comment by matz3** [comment]
It turned out that this is working but really slow.
That is due to internal request handling which is going to be improved with https://github.com/SAP/karma-ui5/pull/150.
