### ISSUE TITLE
Failure on multiple frameworks

### ISSUE THREAD

**Issue by mlenkeit** [SAP/karma-ui5#162]
Currently, `karma-ui5` fails when there's any other Karma framework specified:

https://github.com/SAP/karma-ui5/blob/0bf30f5deffd9a61e784726aa3c9ea5704b7b018/lib/framework.js#L137-L140

I assume this exists for historical reasons and in order to ease the migration from `karma-openui5`, where it was common to maintain multiple frameworks.

Anyway, I like to suggest to turn this error into a warning. After all, it should be my responsibility if I decide to mess up my config 😉

I think there are good reasons to have other frameworks. In this specific case, @CCFenner and me looking into a Karma plugin that will make it easier to integrate with SAP's [jenkins-library](https://github.com/SAP/jenkins-library/). But there are also other Karma plugins that need to be configured as frameworks and shouldn't interfere with `karma-ui5`, e.g. [karma-parallel](https://www.npmjs.com/package/karma-parallel).

Any chance of turning this into a warning rather than an error? Happy to provide a PR...

**Comment by mlenkeit** [comment]
Alternatively, instead of completely removing the error message, how about introducing a blacklist of incompatible Karma plugins? I see that you already have explicit unit tests to prevent `qunit` and `sinon` frameworks to be used along with `ui5`. Again, happy to provide a PR...

/cc @matz3  @RandomByte

**Comment by matz3** [comment]
Thanks 👍I've merged your PR and plan to release a new version this week (probably along with other outstanding fixes/changes).

**Comment by matz3** [comment]
Released with v1.2.0

**Comment by mlenkeit** [comment]
Thanks! 👍
