### ISSUE TITLE
not working with ui5 tooling 2.0

### ISSUE THREAD

**Issue by majany** [SAP/karma-ui5#168]
Hi karma-ui5 team,

I updated my ui5 project to use the newest ui5 tooling v2.0 and also updated the spec version to 2.0 in my ui5.yaml file. Unfortunately the current karma-ui5 version does not support the new spec version.
Starting karma fails with the error:
``
Error: Unsupported specification version 2.0
``
I would appreciate it if you could update karma-ui5 to support the new ui5 tooling version.

Thank you and regards,
Mathäus

**Comment by matz3** [comment]
karma-ui5 v2.0.0 has just been released, which supports the new specVersion.
Details about the release can be found here: https://github.com/SAP/karma-ui5/releases/tag/v2.0.0
