### ISSUE TITLE
Allow alternate ui5.yaml instead of hard-coded one

### ISSUE THREAD

**Issue by petermuessig** [SAP/karma-ui5#169]
Hi @matz3 ,

is it possible that we enable an alternative ui5.yaml file for testing? E.g. if you have livereload in your original file, I would put a ui5-test.yaml next to it without the livereload in the middleware.

THX and BR,
Peter

**Comment by matz3** [comment]
Definitely makes sense to have an `config` option like in the CLI.
I will work on this unless you want to file a PR.

**Comment by petermuessig** [comment]
I did not prepare a PR. I first wanted to discuss this with you... :-)

**Comment by matz3** [comment]
Released with v2.1.0
