### ISSUE TITLE
Screenshots on failure

### ISSUE THREAD

**Issue by shahzeb79** [SAP/karma-ui5#180]
Hi Colleagues,
                     I want to ask is it possible to take browser screenshot at the end of tests execution?
It will be nice if we can have it .

Thanks
Shahzeb

**Comment by matz3** [comment]
Currently there are no concrete plans to integrate this into karma-ui5.
However this could be realized via a selenium or puppeteer launcher, which would be independent of this plugin. As an employee you might also search for "karma-launcher" in GitHub Enterprise.
