### ISSUE TITLE
Project piper / karmaExecuteTests / QUnit is not defined

### ISSUE THREAD

**Issue by Nico31300** [SAP/karma-ui5#227]
Hello,

I'm trying to implement project piper and more specifically the step karmaExecuteTests.

I installed a jenkins on a linux server with the docker:
```
docker run -it --rm -p 8079:80 -u $(id -u):$(id -g) -v "${PWD}":/cx-server/mount/ ppiper/cx-server-companion:latest init-cx-server
chmod +x ./cx-server
./cx-server start
```

Jenkinsfile
```
@Library('piper-lib-os') _
node() {
    stage('prepare') {
        checkout scm
        setupCommonPipelineEnvironment script:this
    }
    
    stage('Test')   {
	  karmaExecuteTests script: this,
		            installCommand: "npm config set strict-ssl false && npm config set @sap:registry https://npm.sap.com && npm install --quiet"
    }
}

```

I think i missed something .... but i cannot find what :( 

karma.conf.js
```
module.exports = function (config) {
  
  config.set({
    frameworks: ['ui5'],
    
    ui5: {
      url: "https://sapui5.hana.ondemand.com"
    },
        
    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_DEBUG,
    
    customLaunchers: {
        'chromeSel': {
            base: 'WebDriver',
            config: { hostname: 'selenium', port: 4444 },
            browserName: 'chrome'
        }
    },
    
    hostname: 'karma',
    port: 9876,
    
    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['chromeSel'],
    
    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: true

  })
}
```

package.json
```
{
	"name": "com.devops.test",
	"version": "2.0.0",
	"description": "Project description",
	"devDependencies": {
		"karma-chrome-launcher" : "latest",
		"karma-webdriver-launcher" : "latest",
		"karma-ui5" : "latest",
		"karma": "^5.1.1"
	},
	"scripts": {
		"karma": "karma start"
	}
}
```

When i execute the step, i got the following error:
QUnit is not defined

Do you have an idea of my mistake ? 

Execution logs

> ```
> [Pipeline] withDockerContainer
> Jenkins seems to be running inside container 0ebc5c817a1bc3886f5c4f8ce53c88bbee417ef92110cec6aa85c0a47cce1f44
> $ docker run -t -d -u 1000:986 --env NO_PROXY=localhost,selenium,$NO_PROXY --env no_proxy=localhost,selenium,$no_proxy --env PIPER_SELENIUM_HOSTNAME=karma --env PIPER_SELENIUM_WEBDRIVER_HOSTNAME=selenium --env PIPER_SELENIUM_WEBDRIVER_PORT=4444 --env http_proxy --env https_proxy --env HTTP_PROXY --env HTTPS_PROXY --network-alias karma --network sidecar-4fa7bff8-3876-470a-ba8d-c4c8c03ffe94 -w /var/jenkins_home/workspace/devops_new_master --volumes-from 0ebc5c817a1bc3886f5c4f8ce53c88bbee417ef92110cec6aa85c0a47cce1f44 -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** node:lts-stretch cat
> $ docker top 1d7231b3ef9ba119d669e44e30b848e40d11f4f092b0bc6f091b6117e17aa900 -eo pid,comm
> [Pipeline] {
> [Pipeline] echo
> [INFO][dockerExecute] Running with sidecar container.
> [Pipeline] sh
> + node --version
> v12.18.3
> + npm --version
> 6.14.6
> [Pipeline] echo
> Unstash content: buildDescriptor
> [Pipeline] unstash
> [Pipeline] echo
> Unstash failed: buildDescriptor (No such saved stash ‘buildDescriptor’)
> [Pipeline] echo
> Unstash content: tests
> [Pipeline] unstash
> [Pipeline] echo
> Unstash failed: tests (No such saved stash ‘tests’)
> [Pipeline] sh
> + cd .
> + npm config set strict-ssl false
> + npm config set @sap:registry https://npm.sap.com
> + npm install --quiet
> npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN com.devops.test@2.0.0 No repository field.
> npm WARN com.devops.test@2.0.0 No license field.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/@ui5/cli/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> audited 1340 packages in 106.109s
> 
> 1 package is looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities
> 
> [Pipeline] sh
> + cd .
> + npm run karma
> 
> > com.devops.test@2.0.0 karma /var/jenkins_home/workspace/devops_new_master
> > karma start
> 
> [36m24 08 2020 10:08:06.977:DEBUG [config]: [39mLoading config /var/jenkins_home/workspace/devops_new_master/karma.conf.js
> [36m24 08 2020 10:08:06.980:DEBUG [config]: [39mautoWatch set to false, because of singleRun
> [36m24 08 2020 10:08:06.981:DEBUG [karma-server]: [39mFinal config Config {
>   LOG_DISABLE: 'OFF',
>   LOG_ERROR: 'ERROR',
>   LOG_WARN: 'WARN',
>   LOG_INFO: 'INFO',
>   LOG_DEBUG: 'DEBUG',
>   frameworks: [ 'ui5' ],
>   protocol: 'http:',
>   port: 9876,
>   listenAddress: '0.0.0.0',
>   hostname: 'karma',
>   httpsServerConfig: {},
>   basePath: '/var/jenkins_home/workspace/devops_new_master',
>   files: [],
>   browserConsoleLogOptions: { level: 'debug', format: '%b %T: %m', terminal: true },
>   customContextFile: null,
>   customDebugFile: null,
>   customClientContextFile: null,
>   exclude: [ '/var/jenkins_home/workspace/devops_new_master/karma.conf.js' ],
>   logLevel: 'DEBUG',
>   colors: true,
>   autoWatch: false,
>   autoWatchBatchDelay: 250,
>   restartOnFileChange: false,
>   usePolling: true,
>   reporters: [ 'progress' ],
>   singleRun: true,
>   browsers: [ 'chromeSel' ],
>   captureTimeout: 60000,
>   pingTimeout: 5000,
>   proxies: {},
>   proxyValidateSSL: true,
>   preprocessors: [Object: null prototype] {},
>   preprocessor_priority: {},
>   urlRoot: '/',
>   upstreamProxy: undefined,
>   reportSlowerThan: 0,
>   loggers: [
>     {
>       type: 'console',
>       layout: { type: 'pattern', pattern: '%[%d{DATE}:%p [%c]: %]%m' }
>     }
>   ],
>   transports: [ 'polling', 'websocket' ],
>   forceJSONP: false,
>   plugins: [
>     'karma-*',
>     [Object: null prototype] {
>       'launcher:chromeSel': [ 'factory', [Function] ]
>     }
>   ],
>   client: {
>     args: [],
>     useIframe: true,
>     runInParent: false,
>     captureConsole: true,
>     clearContext: true
>   },
>   defaultClient: {
>     args: [],
>     useIframe: true,
>     runInParent: false,
>     captureConsole: true,
>     clearContext: true
>   },
>   browserDisconnectTimeout: 2000,
>   browserDisconnectTolerance: 0,
>   browserNoActivityTimeout: 30000,
>   processKillTimeout: 2000,
>   concurrency: Infinity,
>   failOnEmptyTestSuite: true,
>   retryLimit: 2,
>   detached: false,
>   crossOriginAttribute: true,
>   browserSocketTimeout: 20000,
>   cmd: 'start',
>   configFile: '/var/jenkins_home/workspace/devops_new_master/karma.conf.js',
>   ui5: { url: 'https://sapui5.hana.ondemand.com' },
>   customLaunchers: {
>     chromeSel: {
>       base: 'WebDriver',
>       config: { hostname: 'selenium', port: 4444 },
>       browserName: 'chrome'
>     }
>   }
> }
> [36m24 08 2020 10:08:06.982:DEBUG [plugin]: [39mLoading karma-* from /var/jenkins_home/workspace/devops_new_master/node_modules
> [36m24 08 2020 10:08:06.983:DEBUG [plugin]: [39mLoading plugin /var/jenkins_home/workspace/devops_new_master/node_modules/karma-chrome-launcher.
> [36m24 08 2020 10:08:06.989:DEBUG [plugin]: [39mLoading plugin /var/jenkins_home/workspace/devops_new_master/node_modules/karma-coverage.
> [36m24 08 2020 10:08:07.180:DEBUG [plugin]: [39mLoading plugin /var/jenkins_home/workspace/devops_new_master/node_modules/karma-junit-reporter.
> [36m24 08 2020 10:08:07.194:DEBUG [plugin]: [39mLoading plugin /var/jenkins_home/workspace/devops_new_master/node_modules/karma-qunit.
> [36m24 08 2020 10:08:07.195:DEBUG [plugin]: [39mLoading plugin /var/jenkins_home/workspace/devops_new_master/node_modules/karma-ui5.
> [36m24 08 2020 10:08:07.420:DEBUG [plugin]: [39mLoading plugin /var/jenkins_home/workspace/devops_new_master/node_modules/karma-webdriver-launcher.
> [36m24 08 2020 10:08:07.531:DEBUG [plugin]: [39mLoading inlined plugin (defining launcher:chromeSel).
> [36m24 08 2020 10:08:07.540:DEBUG [web-server]: [39mInstantiating middleware
> [32m24 08 2020 10:08:07.594:INFO [karma-server]: [39mKarma v5.1.1 server started at http://karma:9876/
> [32m24 08 2020 10:08:07.594:INFO [launcher]: [39mLaunching browsers chromeSel with concurrency unlimited
> [32m24 08 2020 10:08:07.601:INFO [launcher]: [39mStarting browser chrome via Remote WebDriver
> [36m24 08 2020 10:08:07.601:DEBUG [launcher]: [39mnull -> BEING_CAPTURED
> [36m24 08 2020 10:08:07.602:DEBUG [temp-dir]: [39mCreating temp dir at /tmp/karma-8540939
> [36m24 08 2020 10:08:07.603:DEBUG [WebDriver]: [39mWebDriver config: {"hostname":"selenium","port":4444}
> [36m24 08 2020 10:08:07.603:DEBUG [WebDriver]: [39mBrowser capabilities: {"platform":"ANY","testName":"Karma test","tags":[],"version":"","base":"WebDriver","browserName":"chrome"}
> [36m24 08 2020 10:08:08.490:DEBUG [WebDriver]: [39mSession ID: 7cf575afcf21a3803eb34e4ead567beb
> [36m24 08 2020 10:08:08.521:DEBUG [web-server]: [39mserving: /var/jenkins_home/workspace/devops_new_master/node_modules/karma/static/client.html
> [36m24 08 2020 10:08:08.548:DEBUG [web-server]: [39mserving: /var/jenkins_home/workspace/devops_new_master/node_modules/karma/static/karma.js
> [36m24 08 2020 10:08:08.608:DEBUG [karma-server]: [39mA browser has connected on socket NtLLOXqwJmJ8zJEMAAAA
> [36m24 08 2020 10:08:08.613:DEBUG [web-server]: [39mupgrade /socket.io/?EIO=3&transport=websocket&sid=NtLLOXqwJmJ8zJEMAAAA
> [36m24 08 2020 10:08:08.628:DEBUG [Chrome 84.0.4147.105 (Linux x86_64)]: [39mundefined -> CONNECTED
> [32m24 08 2020 10:08:08.628:INFO [Chrome 84.0.4147.105 (Linux x86_64)]: [39mConnected on socket NtLLOXqwJmJ8zJEMAAAA with id 8540939
> [36m24 08 2020 10:08:08.629:DEBUG [launcher]: [39mBEING_CAPTURED -> CAPTURED
> [36m24 08 2020 10:08:08.629:DEBUG [launcher]: [39mchrome via Remote WebDriver (id 8540939) captured in 1.034 secs
> [36m24 08 2020 10:08:08.630:DEBUG [Chrome 84.0.4147.105 (Linux x86_64)]: [39mCONNECTED -> CONFIGURING
> [36m24 08 2020 10:08:08.637:DEBUG [web-server]: [39mserving: /var/jenkins_home/workspace/devops_new_master/node_modules/karma/static/favicon.ico
> [36m24 08 2020 10:08:08.642:DEBUG [middleware:karma]: [39mcustom files null null null
> [36m24 08 2020 10:08:08.642:DEBUG [middleware:karma]: [39mServing static request /context.html
> [36m24 08 2020 10:08:08.643:DEBUG [web-server]: [39mserving: /var/jenkins_home/workspace/devops_new_master/node_modules/karma/static/context.html
> [36m24 08 2020 10:08:08.655:DEBUG [middleware:source-files]: [39mRequesting /base/node_modules/karma-ui5/dist/browser-bundle.js?9782f34985d6e25e47acb897b972985465a0852f
> [36m24 08 2020 10:08:08.655:DEBUG [middleware:source-files]: [39mFetching /var/jenkins_home/workspace/devops_new_master/node_modules/karma-ui5/dist/browser-bundle.js
> [36m24 08 2020 10:08:08.655:DEBUG [web-server]: [39mserving (cached): /var/jenkins_home/workspace/devops_new_master/node_modules/karma-ui5/dist/browser-bundle.js
> [36m24 08 2020 10:08:08.657:DEBUG [web-server]: [39mserving: /var/jenkins_home/workspace/devops_new_master/node_modules/karma/static/context.js
> [36m24 08 2020 10:08:08.684:DEBUG [middleware:source-files]: [39mRequesting /base/webapp/test/testsuite.qunit.html
> [36m24 08 2020 10:08:08.684:DEBUG [middleware:source-files]: [39mFetching /var/jenkins_home/workspace/devops_new_master/webapp/test/testsuite.qunit.html
> [36m24 08 2020 10:08:08.684:DEBUG [web-server]: [39mserving (cached): /var/jenkins_home/workspace/devops_new_master/webapp/test/testsuite.qunit.html
> [36m24 08 2020 10:08:08.694:DEBUG [middleware:source-files]: [39mRequesting /base/webapp/test/testsuite.qunit.html
> [36m24 08 2020 10:08:08.694:DEBUG [middleware:source-files]: [39mFetching /var/jenkins_home/workspace/devops_new_master/webapp/test/testsuite.qunit.html
> [36m24 08 2020 10:08:08.694:DEBUG [web-server]: [39mserving (cached): /var/jenkins_home/workspace/devops_new_master/webapp/test/testsuite.qunit.html
> [36m24 08 2020 10:08:08.704:DEBUG [middleware:source-files]: [39mRequesting /base/resources/sap/ui/qunit/qunit-redirect.js
> [36m24 08 2020 10:08:08.705:DEBUG [middleware:source-files]: [39mFetching /var/jenkins_home/workspace/devops_new_master/resources/sap/ui/qunit/qunit-redirect.js
> [36m24 08 2020 10:08:08.723:DEBUG [middleware:source-files]: [39mRequesting /base/webapp/test/testsuite.qunit.js
> [36m24 08 2020 10:08:08.723:DEBUG [middleware:source-files]: [39mFetching /var/jenkins_home/workspace/devops_new_master/webapp/test/testsuite.qunit.js
> [36m24 08 2020 10:08:08.723:DEBUG [web-server]: [39mserving (cached): /var/jenkins_home/workspace/devops_new_master/webapp/test/testsuite.qunit.js
> Error: read ECONNRESET
>     at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
> [36m24 08 2020 10:08:08.806:DEBUG [middleware:source-files]: [39mRequesting /base/webapp/test/unit/unitTests.qunit.html
> [36m24 08 2020 10:08:08.806:DEBUG [middleware:source-files]: [39mFetching /var/jenkins_home/workspace/devops_new_master/webapp/test/unit/unitTests.qunit.html
> [36m24 08 2020 10:08:08.806:DEBUG [web-server]: [39mserving (cached): /var/jenkins_home/workspace/devops_new_master/webapp/test/unit/unitTests.qunit.html
> [36m24 08 2020 10:08:08.820:DEBUG [middleware:source-files]: [39mRequesting /base/resources/sap-ui-core.js
> [36m24 08 2020 10:08:08.820:DEBUG [middleware:source-files]: [39mFetching /var/jenkins_home/workspace/devops_new_master/resources/sap-ui-core.js
> [36m24 08 2020 10:08:08.825:DEBUG [middleware:source-files]: [39mRequesting /base/resources/sap/ui/thirdparty/qunit-2.css
> [36m24 08 2020 10:08:08.825:DEBUG [middleware:source-files]: [39mFetching /var/jenkins_home/workspace/devops_new_master/resources/sap/ui/thirdparty/qunit-2.css
> [36m24 08 2020 10:08:08.828:DEBUG [middleware:source-files]: [39mRequesting /base/resources/sap/ui/thirdparty/qunit-2.js
> [36m24 08 2020 10:08:08.828:DEBUG [middleware:source-files]: [39mFetching /var/jenkins_home/workspace/devops_new_master/resources/sap/ui/thirdparty/qunit-2.js
> [36m24 08 2020 10:08:08.832:DEBUG [middleware:source-files]: [39mRequesting /base/resources/sap/ui/qunit/qunit-junit.js
> [36m24 08 2020 10:08:08.832:DEBUG [middleware:source-files]: [39mFetching /var/jenkins_home/workspace/devops_new_master/resources/sap/ui/qunit/qunit-junit.js
> [36m24 08 2020 10:08:08.833:DEBUG [middleware:source-files]: [39mRequesting /base/resources/sap/ui/qunit/qunit-coverage.js
> [36m24 08 2020 10:08:08.833:DEBUG [middleware:source-files]: [39mFetching /var/jenkins_home/workspace/devops_new_master/resources/sap/ui/qunit/qunit-coverage.js
> [36m24 08 2020 10:08:08.835:DEBUG [middleware:source-files]: [39mRequesting /base/webapp/test/unit/unitTests.qunit.js
> [36m24 08 2020 10:08:08.835:DEBUG [middleware:source-files]: [39mFetching /var/jenkins_home/workspace/devops_new_master/webapp/test/unit/unitTests.qunit.js
> [36m24 08 2020 10:08:08.835:DEBUG [web-server]: [39mserving (cached): /var/jenkins_home/workspace/devops_new_master/webapp/test/unit/unitTests.qunit.js
> Error: read ECONNRESET
>     at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
> Error: read ECONNRESET
>     at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
> Error: read ECONNRESET
>     at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
> Error: read ECONNRESET
>     at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
> Error: read ECONNRESET
>     at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
> Chrome 84.0.4147.105 (Linux x86_64) ERROR
>   Uncaught ReferenceError: QUnit is not defined
>   at webapp/test/unit/unitTests.qunit.js:2:1
>   
>   ReferenceError: QUnit is not defined
>       at webapp/test/unit/unitTests.qunit.js:2:1
> 
> [36m24 08 2020 10:08:08.879:DEBUG [middleware:source-files]: [39mRequesting /base/webapp/test/integration/opaTests.qunit.html
> [36m24 08 2020 10:08:08.880:DEBUG [middleware:source-files]: [39mFetching /var/jenkins_home/workspace/devops_new_master/webapp/test/integration/opaTests.qunit.html
> [36m24 08 2020 10:08:08.880:DEBUG [web-server]: [39mserving (cached): /var/jenkins_home/workspace/devops_new_master/webapp/test/integration/opaTests.qunit.html
> [36m24 08 2020 10:08:08.882:DEBUG [Chrome 84.0.4147.105 (Linux x86_64)]: [39mCONFIGURING -> CONNECTED
> 
> [36m24 08 2020 10:08:08.884:DEBUG [launcher]: [39mCAPTURED -> BEING_KILLED
> [36m24 08 2020 10:08:08.885:DEBUG [launcher]: [39mBEING_KILLED -> BEING_FORCE_KILLED
> [36m24 08 2020 10:08:08.885:DEBUG [karma-server]: [39mRun complete, exiting.
> [36m24 08 2020 10:08:08.885:DEBUG [launcher]: [39mDisconnecting all browsers
> [36m24 08 2020 10:08:08.885:DEBUG [launcher]: [39mBEING_FORCE_KILLED -> BEING_FORCE_KILLED
> [36m24 08 2020 10:08:08.886:DEBUG [proxy]: [39mDestroying proxy agents
> [36m24 08 2020 10:08:08.888:DEBUG [middleware:source-files]: [39mRequesting /base/resources/sap-ui-core.js
> [36m24 08 2020 10:08:08.889:DEBUG [middleware:source-files]: [39mFetching /var/jenkins_home/workspace/devops_new_master/resources/sap-ui-core.js
> [36m24 08 2020 10:08:08.890:DEBUG [middleware:source-files]: [39mRequesting /base/resources/sap/ui/thirdparty/qunit-2.css
> [36m24 08 2020 10:08:08.890:DEBUG [middleware:source-files]: [39mFetching /var/jenkins_home/workspace/devops_new_master/resources/sap/ui/thirdparty/qunit-2.css
> [36m24 08 2020 10:08:08.891:DEBUG [middleware:source-files]: [39mRequesting /base/resources/sap/ui/thirdparty/qunit-2.js
> [36m24 08 2020 10:08:08.892:DEBUG [middleware:source-files]: [39mFetching /var/jenkins_home/workspace/devops_new_master/resources/sap/ui/thirdparty/qunit-2.js
> [36m24 08 2020 10:08:08.893:DEBUG [middleware:source-files]: [39mRequesting /base/resources/sap/ui/qunit/qunit-junit.js
> [36m24 08 2020 10:08:08.893:DEBUG [middleware:source-files]: [39mFetching /var/jenkins_home/workspace/devops_new_master/resources/sap/ui/qunit/qunit-junit.js
> [36m24 08 2020 10:08:08.894:DEBUG [middleware:source-files]: [39mRequesting /base/webapp/test/integration/opaTests.qunit.js
> [36m24 08 2020 10:08:08.894:DEBUG [middleware:source-files]: [39mFetching /var/jenkins_home/workspace/devops_new_master/webapp/test/integration/opaTests.qunit.js
> [36m24 08 2020 10:08:08.894:DEBUG [web-server]: [39mserving (cached): /var/jenkins_home/workspace/devops_new_master/webapp/test/integration/opaTests.qunit.js
> Error: socket hang up
>     at connResetException (internal/errors.js:610:14)
>     at TLSSocket.socketCloseListener (_http_client.js:400:25)
>     at TLSSocket.emit (events.js:327:22)
>     at net.js:674:12
>     at TCP.done (_tls_wrap.js:567:7)
> Error: socket hang up
>     at connResetException (internal/errors.js:610:14)
>     at TLSSocket.socketCloseListener (_http_client.js:400:25)
>     at TLSSocket.emit (events.js:327:22)
>     at net.js:674:12
>     at TCP.done (_tls_wrap.js:567:7)
> Error: socket hang up
>     at connResetException (internal/errors.js:610:14)
>     at TLSSocket.socketCloseListener (_http_client.js:400:25)
>     at TLSSocket.emit (events.js:327:22)
>     at net.js:674:12
>     at TCP.done (_tls_wrap.js:567:7)
> Error: socket hang up
>     at connResetException (internal/errors.js:610:14)
>     at TLSSocket.socketCloseListener (_http_client.js:400:25)
>     at TLSSocket.emit (events.js:327:22)
>     at net.js:674:12
>     at TCP.done (_tls_wrap.js:567:7)
> [32m24 08 2020 10:08:08.955:INFO [WebDriver]: [39mKilled Karma test.
> [36m24 08 2020 10:08:08.956:DEBUG [launcher]: [39mProcess chrome via Remote WebDriver exited with code 0 and signal null
> [36m24 08 2020 10:08:08.957:DEBUG [temp-dir]: [39mCleaning temp dir /tmp/karma-8540939
> [36m24 08 2020 10:08:08.961:DEBUG [launcher]: [39mFinished all browsers
> [36m24 08 2020 10:08:08.962:DEBUG [launcher]: [39mBEING_FORCE_KILLED -> FINISHED
> [36m24 08 2020 10:08:08.962:DEBUG [launcher]: [39mFINISHED -> FINISHED
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! com.devops.test@2.0.0 karma: `karma start`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the com.devops.test@2.0.0 karma script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> ```

Thank you very much

**Comment by shahzeb79** [comment]
Try to load qunit like:
<script type="text/javascript" src="../resources/sap/ui/thirdparty/qunit.js"></script>

In your in your testsuite html file

**Comment by Nico31300** [comment]
> Try to load qunit like:
> 
> <script type="text/javascript" src="../resources/sap/ui/thirdparty/qunit.js"></script>
> In your in your testsuite html file
Thank you for you answer, but still the same issue.

**Comment by codeworrior** [comment]
From the log, the requests looked ok for me. qunit-2 was requested and the server could respond. 

Assuming that this was the only usage of qunit-2, I thought about other reasons for QUnit not to be defined. But without seeing the test pages, this was a bit difficult. Can we see your test project somewhere?

**Comment by Nico31300** [comment]
> From the log, the requests looked ok for me. qunit-2 was requested and the server could respond.
> 
> Assuming that this was the only usage of qunit-2, I thought about other reasons for QUnit not to be defined. But without seeing the test pages, this was a bit difficult. Can we see your test project somewhere?

You can find it here: https://github.com/Nico31300/devops/

**Comment by codeworrior** [comment]
Mhmm, I might be totally wrong, but to me, the relative paths in the unitTests.qunit.html look wrong. They work for WebIDE on Neo as the neoapp.json maps the path /resources as well as the path /webapp/resources all to the same UI5 service.

Without the help of the neoapp.json, the relative paths point outside the webapp and might not work. 

Reading the log now again, I'm missing "serving" entries for all the resources requested by the unitTests.qunit.html.

Sorry if I waste your time with a wrong guess, but can you give it a try and replace all the ../../../ by a ../../ (just two levels up, not three)?

**Comment by Nico31300** [comment]
Don't be sorry i will give it a try!

**Comment by Nico31300** [comment]
I got your point about neoapp.json, maybe you are right. I performed some tests to change relative paths:

href="../../../resources/sap/ui/thirdparty/qunit-2.css"
```
[36m25 08 2020 13:46:02.934:DEBUG [middleware:source-files]: [39mFetching /var/jenkins_home/workspace/devops_new_master/resources/sap/ui/thirdparty/qunit-2.css
[36m25 08 2020 13:46:02.935:DEBUG [middleware:source-files]: [39mRequesting /base/resources/sap/ui/thirdparty/qunit-2.js
```

href="../../resources/sap/ui/thirdparty/qunit-2.css"
```
[36m25 08 2020 13:28:54.742:DEBUG [middleware:source-files]: [39mRequesting /base/webapp/resources/sap/ui/thirdparty/qunit-2.css
[36m25 08 2020 13:28:54.742:DEBUG [middleware:source-files]: [39mFetching /var/jenkins_home/workspace/devops_new_master/webapp/resources/sap/ui/thirdparty/qunit-2.css
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
```

href="https://sapui5.hana.ondemand.com/sap/ui/thirdparty/qunit-2.css">
No line in debug for requesting/fetching and
```
Chrome 84.0.4147.105 (Linux x86_64) ERROR
  Disconnected, because no message in 30000 ms.
```

I don't know where the test page is getting resources. The folder 
/var/jenkins_home/workspace/devops_new_master/ does not contains any resources folder

```
jenkins@0ebc5c817a1b:~/workspace/devops_new_master$ ls -l
total 36688
drwxr-xr-x   2 jenkins 986     4096 Aug 21 14:23 'Chrome_84.0.4147.105_(Linux_x86_64)'
-rw-r--r--   1 jenkins 986      385 Aug 24 14:45  Jenkinsfile
-rw-r--r--   1 jenkins 986        9 Jul 30 09:35  README.md
-rw-r--r--   1 jenkins 986     1001 Aug 24 15:38  karma.conf.js
-rw-r-xr-x   1 jenkins 986      318 Aug 21 13:07  karmaExecuteTests_errorDetails.json
-rw-r--r--   1 jenkins 986      199 Jul 30 09:35  mta.yaml
-rw-r--r--   1 jenkins 986     1033 Jul 30 09:35  neo-app.json
drwxr-xr-x 470 jenkins 986    20480 Aug 25 11:54  node_modules
-rw-r--r--   1 jenkins 986   224689 Aug 25 13:45  package-lock.json
-rw-r--r--   1 jenkins 986      346 Aug 25 13:45  package.json
-rwxr-xr-x   1 jenkins 986 37285888 Aug 21 11:47  piper
drwxr-xr-x   8 jenkins 986     4096 Aug 21 09:43  webapp
```

**Comment by matz3** [comment]
@Nico31300 I could successfully verify the current state of your repository. I've used the Chrome launcher instead of Selenium, but this should be independent of the mentioned issue. It seems you have changed some things after your last comment.
Is it now working for you as well?

Would you mind creating a support ticket for the WebIDE template so that it will be updated with the correct paths?

As this isn't an issue with the karma-ui5 plugin, I'm closing this issue.

**Comment by Nico31300** [comment]
Hello,

Yes i have done some update in the code, now it's working locally with karma-ui5 plugin.

My issue is now related to project piper, i open an issue in [jenkins-library ](https://github.com/SAP/jenkins-library/issues/1957).

Thank you all for your help.
