### ISSUE TITLE
Error with componen-preload.js in OPA tests

### ISSUE THREAD

**Issue by MaximShmyrev** [SAP/karma-ui5#320]
Hey team,

During running from CI of OPA tests with karma there is an error
![image](https://user-images.githubusercontent.com/35171795/121402269-57af0d00-c962-11eb-8c76-3a808032b5c8.png)
there a request for Component-preload.js, but we're doing these tests before build, so we don't have Component-preload.js yet..
And like a result whole stage in CI fail..is any way to exclude this request? And why it's requested in general, there is nothing in OPA tests itself that can require Component-preload.js

**Comment by codeworrior** [comment]
Normally, `Component-preload.js` is requested whenever you create a component instance for which the code has not been loaded yet.

You can disable the request in your test by adding the attribute 
```html
    data-sap-ui-xx-componentPreload="off"
```
 to the UI5 bootstrap configuration (or by adding the URL parameter `sap-ui-xx-componentPreload=off`).

**Comment by MaximShmyrev** [comment]
your suggestion helped, many thanks!
