### ISSUE TITLE
No middleware provided issue

### ISSUE THREAD

**Issue by shahzeb79** [SAP/karma-ui5#351]
Hi colleagues, we were running karma-ui5 from long time on 2.3.0 version, but today i was testing it on 2.3.4 but get error:
`Error: No provider for "middleware:ui5--serveResources"! (Resolving: webServer -> middleware:ui5--serveResources)`

can you suggest what has changed and needs to be modified?

**Comment by matz3** [comment]
I think those changes are related, but are only meant to be internal, so it shouldn't be affecting any users of the plugin:
https://github.com/SAP/karma-ui5/compare/v2.3.0...v2.3.4#diff-92bbac9a308cd5fcf9db165841f2d90ce981baddcb2b1e26cfff170929af3bd1

Could you please share your configuration? Are you configuring or referring to the `ui5--serveResources` middleware in your config/code?

**Comment by shahzeb79** [comment]
Hi mathias,
I found the issue actually, i had an extension of framework.js for our usecase but it was older one, so now i extended our [framework.js](https://github.wdf.sap.corp/S4FIORI-CD/karmaRunner/blob/master/framework.js) with respect to framework file of new version and now its working fine. Thanks alot.
