### ISSUE TITLE
Activate UI5 Tooling's verbose  mode within karma

### ISSUE THREAD

**Issue by LukasHeimann** [SAP/karma-ui5#408]
Hi everyone!

In my project, I want to use `karma-ui5` together with the wonderful UI5 tooling. However, I'm currently facing an issue ([the tooling fails to provide random files from ui5 libraries](https://github.com/SAP/karma-ui5/issues/411), https://github.com/SAP/karma-ui5/issues/411) I'd like to debug. I use `--log-level debug` at the karma cli, `browserConsoleLogOptions` in my karma options.

However, I can't see the `--verbose` logs of ui5 cli. How can I activate those? It doesn't seem to happen by default, and there isn't any docs on how to do so...

Thank you for your response! Kind regards
Lukas

**Comment by plantago** [comment]
Try to set the environment variable `export UI5_LOG_LVL=verbose` before running your `npm` script.

```sh
export UI5_LOG_LVL=verbose
npm run karma
```

or

```sh
UI5_LOG_LVL=verbose npm run karma
```

**Comment by LukasHeimann** [comment]
Thank you for providing this workaround, that is really helpful! I guess we could still keep this open to have a tighter integration with Karma's configuration, though...

**Comment by d3xter666** [comment]
Hi @LukasHeimann,

Now we have described this scenario in UI5 Tooling's documentation. Please check it here: https://sap.github.io/ui5-tooling/stable/pages/Troubleshooting/#changing-the-log-level
