### ISSUE TITLE
Adjust plugin for HTML mode

### ISSUE THREAD

**Issue by romaniam** [SAP/karma-ui5#45]
When html is used as mode. 

* If url is not set, then UI5 middleware should be used
* files declaration is not required anymore
* If multiple frameworks are used, then no errors should be thrown
* in the initHTML method the pattern should be adjusted e.g. /base/webapp prefix for middleware

The documentation must be adjusted properly.

**Comment by matz3** [comment]
Done with https://github.com/SAP/karma-ui5/pull/46, docs with be updated with https://github.com/SAP/karma-ui5/pull/50
