### ISSUE TITLE
singleRun=false and multiple tests - only one module displayed in the browser?

### ISSUE THREAD

**Issue by wozjac** [SAP/karma-ui5#505]
Hello,

the case:

Using easy-ui5 generator, choosing a library project, version of SAPUI5 1.108.4.
Project is generated with one source file and tests.

When you adjust the test script to keep Karma opened:
```json
"testsuite": "ui5 serve --open test-resources/com/myorg/sampleLib/qunit/testsuite.qunit.html",
 "test": "karma start --browsers=Chrome --singleRun=false"
```
and run `npm test` it looks OK. 4 test cases executed.

Now add another file to `src`:
```js
sap.ui.define(
	["sap/ui/base/Object"],
	function (BaseObject) {
		return BaseObject.extend("com.myorg.sampleLib.Sample", {
			getA: function (sCustomerID) {
				return 'A';
			},
		});
	},
	true
);
```
and test for it:
```js
sap.ui.define([
	"com/myorg/sampleLib/Sample"
], function(Sample) {
	"use strict";

	QUnit.module("Sample Tests");

	QUnit.test("Test A", function(assert) {
		var sample = new Sample();
		assert.equal(sample.getA(), "A", "Check A");
	});
});
```
registered in testsuite.qunit.js:
```js
sap.ui.define(function() {
	"use strict";

	return {
		name: "QUnit TestSuite for com.myorg.sampleLib",
		defaults: {
			bootCore: true,
			ui5: {
				libs: "sap.ui.core,com.myorg.sampleLib",
				theme: "sap_fiori_3",
				noConflict: true,
				preload: "auto"
			},
			qunit: {
				version: 2,
				reorder: false
			},
			sinon: {
				version: 4,
				qunitBridge: true,
				useFakeTimers: false
			},
			module: "./{name}.qunit"
		},
		tests: {
			// test file for the Example control
			Example: {
				title: "QUnit Test for Example",
				_alternativeTitle: "QUnit tests: com.myorg.sampleLib.Example"
			},
                        Sample: {
                                title: "QUnit test for Sample"
                       }
		}
	};

});
```
When you run `npm run testsuite` - it is ok, all 4 + 1 new tests are executed.
Now run `npm test`, Chrome opens and in the log all 5 tests are executed:

![screen1](https://user-images.githubusercontent.com/20969653/208435746-1a0d41dc-2888-4438-a0ff-08e92885bbd6.png)

But in the Chrome browser you see only the module for Sample.js

![screen2](https://user-images.githubusercontent.com/20969653/208435911-195c99f4-c32e-4567-97f5-15379612a32d.png)
 
The previous two modules from Example.js are not present and Sample.js is picked because it is the last (alphabetically). If you changed the test file name to `DSample.qunit.js` and in the testsuite.qunit.js:
```js
tests: {
  // test file for the Example control
  Example: {
    title: "QUnit Test for Example",
  _alternativeTitle: "QUnit tests: com.myorg.sampleLib.Example"
  },
  DSample: {
    title: "QUnit test for Sample"
  }
}
```
then only modules from Example will be shown:

![scree3](https://user-images.githubusercontent.com/20969653/208436835-23dfdf28-0e69-4df0-83f6-443cad7d7f28.png)

Even if you make a test from DSample failing, it will be shown as failed in the console:
![screen4](https://user-images.githubusercontent.com/20969653/208437109-b2d1ee3b-3dc8-4778-bfc4-4260ac134ecc.png)

but not in Chrome, which will show just successful execution of Example modules.

How to get all modules taken into account?

Best Regards,
Jacek

**Comment by matz3** [comment]
When using `singleRun=false` all tests are executed and then the browser stays open, which shows the last testpage executed. When you are using the karma `watch` mode, the tests will be executed again after changing source files.

You simply can't see the other tests because they are executed so fast that the UI might not even be fully rendered as soon as the tests are done.

**Comment by matz3** [comment]
I hope that this helps understanding the behaviour. Test pages will be closed once they are done to free memory. For debugging test you can just open them without karma or specify it as the `testpage` configuration.

**Comment by wozjac** [comment]
Thanks for prompt response.
I have compared this to the behavior from one old project which uses Grunt to set Karma in watch mode.

testsuite file:
```js
window.suite = function() {
	"use strict";

	// eslint-disable-next-line new-cap
	var oSuite = new parent.jsUnitTestSuite(),
		sContextPath = location.pathname.substring(0, location.pathname.lastIndexOf("/") + 1);

	// Add test pages to this test suite
	oSuite.addTestPage(sContextPath + "unit/unitTests.qunit.html");

	return oSuite;
};
```

then `unit` folder specifies all qunit tests in `allTests.js` and then `unitTest.qunit.html` page has the section:
```html
<script>
  /* global QUnit */
  QUnit.config.autostart = false;
  sap.ui.getCore().attachInit(function () {
  sap.ui.require(["test/my/ns/allTests"], function() {
    QUnit.start();
  });
});
</script>
```
Then there are separate qunit files with tests which also specifies `QUnit.module(...)`.
In this case running Karma in watch mode shows all modules in Chrome, so my expectation was based on this behavior.
