### ISSUE TITLE
Transitive dependency express-js 4.17.1 considered vulnerable

### ISSUE THREAD

**Issue by BavithiraG** [SAP/karma-ui5#549]
Hello Team,

I use karma-ui version 2.4.0 which brings the transitive dependency of expressjs with version 4.17.1.
The latest version of karma-ui5 still uses the 4.17.1 version of expressjs which is considered as vulnerable in security scan.
Please let me know if the version of expressjs will be updated in the upcoming release.

Thanks in advance.

**Comment by matz3** [comment]
Both [karma-ui5](https://github.com/SAP/karma-ui5/blob/v3.0.2/package.json#L102) and [@ui5/server](https://github.com/SAP/ui5-server/blob/v3.1.1/package.json#L126) define a proper range to all new 4.x.x versions of express.
Also in v2 [the range allows newer versions](https://github.com/SAP/karma-ui5/blob/v2.4.0/package.json#L56).

Please make sure to update your lockfiles (e.g. package-lock.json) to make sure the latest version of express is used.
I don't see anything that could be done within this project.
