### ISSUE TITLE
Library dont work if some files are not present

### ISSUE THREAD

**Issue by shahzeb79** [SAP/karma-ui5#55]
Hi Colleagues,
                     This library don't work if we dont have testsuite.qunit.html and testsuite.qunit.js files in our test folder. Which is not good i guess like i just placed these files from a different project and my tests start running. If they are really important, than you must mention in documentation to have these files present in test folder.
We seriously spent hours to find it out.

Thanks
Shahzeb

**Comment by matz3** [comment]
Which error were you facing before adding the testsuite files to your project?
We tried to create meaningful error messages when something is missing or not as expect.

Would a link to our Developer Guide have helped you with that?
e.g. https://openui5.hana.ondemand.com/#/topic/a9c949cd49a148b38228110540667930
