### ISSUE TITLE
Karma-UI5 should respect `configPath` for `autoDetectType`

### ISSUE THREAD

**Issue by petermuessig** [SAP/karma-ui5#595]
In the function `autoDetectType` we hard-coded the `ui5.yaml` but we could also consider to use the `configPath` instead, right?

https://github.com/SAP/karma-ui5/blob/main/lib/framework.js#L305

**Comment by matz3** [comment]
True. This is a bug and should be fixed. `configPath` should be considered.

**Comment by petermuessig** [comment]
🎉
