### ISSUE TITLE
Reporting into cucumber-style pretty reports.json

### ISSUE THREAD

**Issue by HoffmannThomas** [SAP/karma-ui5#60]
Hi,

is it possible to generate the same reports.json like in cucumber runners? The default Karma JUnit output is a bit ugly, even with the test analyzer. It would be much prettier (and provide more information) if I could use the cucumber reporter or living docs in Jenkins:

**What I get:**
![image](https://user-images.githubusercontent.com/8157678/57933715-45b32b00-78be-11e9-9eac-6c33d7bc769e.png)

**What I can make out if it:**
![image](https://user-images.githubusercontent.com/8157678/57933668-2d431080-78be-11e9-9f5f-05f3334b3b8b.png)

**What I really want:**
![image](https://user-images.githubusercontent.com/8157678/57933868-a17db400-78be-11e9-8c37-3f92926c8cc4.png)

![image](https://user-images.githubusercontent.com/8157678/57934077-1e109280-78bf-11e9-8f6e-8477389a71c8.png)

Best regards,
Thomas

**Comment by matz3** [comment]
Could you please tell how this is related to the UI5 plugin? Is it because the `html` mode only supports QUnit as a testing framework?

To me this rather sounds like a requirement for an existing or new reporter plugin, which is not within this project's scope.

**Comment by HoffmannThomas** [comment]
> Could you please tell how this is related to the UI5 plugin? Is it because the `html` mode only supports QUnit as a testing framework?
> 
> To me this rather sounds like a requirement for an existing or new reporter plugin, which is not within this project's scope.

I'm very sorry but it turns out [karma-cucumber-reporter](https://github.com/akullpp/karma-cucumber-reporter) works very well when configured correctly.

**Comment by matz3** [comment]
No worries, glad to hear that you could get it working 👍

**Comment by HoffmannThomas** [comment]
Hi,

and again I'm sorry but there were difficulties. The plugin I mentioned expects a different history structure. After adapting this I noticed that the step information is missing completely.

I will contact you directly to show you what I found so far.

Regards,
Thomas
