### ISSUE TITLE
karma-ui5 usage in jenkins without internet access

### ISSUE THREAD

**Issue by anoojrkrishnan** [SAP/karma-ui5#69]
I wanted to use karma-ui5 plugin in jenkins build server to run qunit testcases of sap ui5 application. The below is my configuration
 ui5: {
      url: "https://openui5.hana.ondemand.com",
      mode: "script",
      config: {
        bindingSyntax: "complex",
        compatVersion: "edge",
        async: true,
        libs: "sap.ui.core, sap.m, sap.ui.layout",
      }
}
It is working fine in local and the session is getting timeout in jenkins server as it does not have access to "https://openui5.hana.ondemand.com". Can I specify the path to sap-ui-core.js directly here in url property? I see in the source code url value is getting concatenated with "/resources/sap-ui-core.js" and being used. 

Thanks,
Anooj

**Comment by matz3** [comment]
You might use the [UI5 Tooling](https://github.com/SAP/ui5-tooling) with the OpenUI5 npm dependencies to have a UI5 downloaded locally.
[OpenUI5 Sample App](https://github.com/SAP/openui5-sample-app) can be taken as reference.
