### ISSUE TITLE
QUnit is not defined if @sap/ui5-builder-webide-extension is present

### ISSUE THREAD

**Issue by jonaszuberbuehler** [SAP/karma-ui5#75]
The last step described at https://help.sap.com/viewer/825270ffffe74d9f988a0f0066ad59f0/CF/en-US/96e7826ed3e747e6b0aac68699d92bfa.html seems to somehow break the karma plugin. I'm getting 404s in the console for all the `/resources/sap/...` files which eventually results in the error message `Uncaught ReferenceError: QUnit is not defined`. Removing the following entry

```
"ui5": {
    "dependencies": [
        "@sap/ui5-builder-webide-extension"
    ]
}
```

from package.json fixes this issue, but breaks `npm run build`.

**Comment by matz3** [comment]
@jonaszuberbuehler I guess you also have dependencies to the OpenUI5 npm packages in your project, right?
In that case, you also need to add those into the list of UI5 dependencies, e.g.
```diff
 "ui5": {
     "dependencies": [
         "@sap/ui5-builder-webide-extension",
+        "@openui5/sap.ui.core"
     ]
 }
```

**Comment by jonaszuberbuehler** [comment]
@matz3 Perfect, thanks! Could you point me to a documentation on the ui5 settings within package.json? I wrongly assumed that having the openui5 packages in the dependencies would be sufficient.
